### PR TITLE
Increase code coverage

### PR DESCRIPTION
**Pull request by ahcorde**
I added some tests to increase the code coverage

### CODE REVIEW

**Comment by chapulina** [comment]
Could you trigger tests and post the code coverage result here? Thanks

**Comment by ahcorde** [comment]
@chapulina I run codecov in [my personal account]( https://codecov.io/gh/ahcorde/class_loader/commit/33ec7c6b7a645620246277a90add1fe7ad8af2a7). It's 90.16%

**Comment by ahcorde** [comment]
or in the buildfarm https://ci.ros2.org/job/ci_linux_coverage/85/cobertura/src_ros_class_loader_include_class_loader/

**Comment by chapulina** [comment]
Thanks, @ahcorde . Do you know why the results are different between codecov and jenkins?

**Review by chapulina — APPROVED** [review]

**Comment by ahcorde** [comment]
Not really, we will need to improve the coverage a little bit more. I will figure it out.

**Comment by wjwwood** [comment]
@ahcorde did you run CI on this? It is causing new compiler warnings I think:

https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1544/gcc/new/

**Comment by ahcorde** [comment]
@wjwwood I forgot to run it. Fixing the warning in this PR https://github.com/ros/class_loader/pull/151

**Comment by wjwwood** [comment]
Please try to remember that in the future. Btw, the automated CI also caught this:

http://build.ros2.org/job/Fpr__class_loader__ubuntu_focal_amd64/5/

It could be seen from this pr's merge button...

**Pull request merged**
