### PR TITLE
fix CI missing catkin_pkg and console_bridge_vendor

### PR DESCRIPTION
**Pull request by dirk-thomas**
As mentioned in https://github.com/ros/class_loader/pull/103#issuecomment-419299945

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@mikaelarguedas @nuclearsandwich I am not sure if / how the CI build is supposed to work on macOS for this repo. I tried to at least install the missing `catkin_pkg` package as well as clone `console_bridge_vendor` but it seems to not be enough. I will leave it up to you to follow up on this PR (and the referenced bugfix PR).

**Comment by mikaelarguedas** [comment]
It looks like travis doesnt support Python for MacOS at the moment: https://github.com/travis-ci/travis-ci/issues/2312 (brew workaround detailed at https://github.com/travis-ci/travis-ci/issues/2312#issuecomment-289140791).

This has been broken for a long time and never made it up the priority list (the `bouncy` branch is using `build.ros2.org` for testing and the `ros2` branch is currently tested manually with `ci.ros2.org` like the other ros2 repos).

Maybe this PR is a good time to consider using colcon instead of a local build of ament_tools?

**Comment by mikaelarguedas** [comment]
see https://github.com/ros/class_loader/pull/106 for a PR superseeding this one

**Comment by mikaelarguedas** [comment]
closing as #106 addressed the CI issues. thanks @dirk-thomas and @yechun1 for reporting

**Pull request closed without merging**
