### PR TITLE
c++14 ?

### PR DESCRIPTION
**Pull request by mikaelarguedas**
@codebot could you give some input here ? I noticed that this branch was tested along all cpp14 branches but has never been merged. Feel free to close this PR if the merge has been postponed/discarded on purpose

### CODE REVIEW

**Comment by dirk-thomas** [comment]
ROS 2 already uses a forked branch named `ros2`. So ROS 1 isn't relevant in this case.

But Travis CI is failing for this.

**Comment by mikaelarguedas** [comment]
I think the only repository that doesn't have a dedicated ros2 branch currently is [console_bridge](https://github.com/ros2/ros2/blob/master/ros2.repos#L146-L149). I think that every repo having a dedicated ros2 branch can be updated along the rest of the ros2 code.

Yes travis is failing on the new flag. AFAIK travis has been failing for a few PRs already. So I'm wondering if the merge policy for the ros2 branch should be:
 * passing both travis/appveyor and ros2 buildfarm
 * ros2 buildfarm is enough for the ros2 branch

**Comment by dirk-thomas** [comment]
Since Travis uses Trusty it doesn't seem to support `-std=c++14`. I don't the argument that the CI has failed before is reasonable. So either we need to modify the Travis or not use C++14.

So the first question imo would be why does this package have to use it in the first place? All the code in this package compiles fine with C++11. And the headers don't even require that afaik.

**Comment by mikaelarguedas** [comment]
yes there is no use of any c++14 feature in this package yet. I think that the only repository using some c++14 is `examples` for now.
I thought we updated all packages for consistency rather than a case by case approach where we convert only if and when needed. If the decision is to update everything in the ros2 org at once but update other packages only when necessary I'm totally fine with it. In the case of ROS1 packages that will have the advantage of keeping the diff short and readable if we decide to backport some changes.

I just didn't know if there has been any discussion on that matter or if this branch was just forgotten along the way so I wanted to raise the question.

**Comment by dirk-thomas** [comment]
The fact that it has diverged is just because we didn't take the time to carefully consider what can be done in master but move forward with it for ROS 2 as fast as possible. I think on goal would be to merge as many (at best all) changes from the `ros2` branch to `master` at some point. Therefore I would avoid any unnecessary changes on the `ros2` branch - especially if they are unlikely to be backportable.

**Comment by mikaelarguedas** [comment]
Agreed, thanks for the feedback. Closing this

**Comment by dirk-thomas** [comment]
Should the branch then be deleted?

**Comment by dirk-thomas** [comment]
The question is still of the branch can be deleted now.

**Comment by mikaelarguedas** [comment]
Branch has been deleted 9 hours ago

**Comment by dirk-thomas** [comment]
Sorry for the noise. I shouldn't check those things from a phone...

**Comment by mikaelarguedas** [comment]
no worries :wink:

**Pull request closed without merging**
