### PR TITLE
fix non-defined variable

### PR DESCRIPTION
**Pull request by dbcesar**
I was having problem here because "CATKIN_PACKAGE_BIN_DESTINATION" was not declared. 

```
 install(PROGRAMS scripts/class_loader_headers_update.py
   DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
```

Since the CATKIN_GLOBAL_BIN_DESTINATION was declared twice I assumed it wanted to refer to CATKIN_PACKAGE. 

If I assumed it wrong please let me know then I change it.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@dbcesar yeah the duplicated line looks wrong indeed.

Can you please provide more information and a way to reproduce the issue you are facing?
It looks like you're building on a system that doesnt have `catkin` installed, is that correct ?
That means you're trying to build with only pure CMake?

**Comment by dbcesar** [comment]
I'm installing it using [autoproj](https://github.com/rock-core/autoproj) a package manager which calls CMake behind it.  

In my case, I dont have catkin installed and I think this is sufficient to reproduce the error. 

Let me know if I can clarify anything else.

**Comment by mikaelarguedas** [comment]
Thanks for the clarification.

**Review by mikaelarguedas — DISMISSED** [review]
LGTM, thanks for the contribution!

**Comment by mikaelarguedas** [comment]
@dbcesar I have one more question: in your workflow you expect the executables to be installed on the path (in the bin folder) and not in libexec (that is the location used by rosrun to avoid executable name collisions across packages). Is that correct?

**Comment by dbcesar** [comment]
Yes. I expect the executables to be installed inside "<my_workspace_dir>/install/bin".

**Comment by mikaelarguedas** [comment]
@dirk-thomas I see that you reviewed the original PR to add support for non-catkin builds, can you please have a look and provide feedback if any ?
Thanks!

**Comment by dirk-thomas** [comment]
I don't mind where the script is being installed to in the "non-catkin" case. But the current patch changes the location in the "catkin" case to be `bin` rather than `lib/catkin` (which seems to be beyond the scope of the issue title "fix non-defined variable"). If that is intentional for the "catkin" case that is fine with me. I only think the location of the script should be consistent and not change between the "catkin" and "non-catkin" case.

**Comment by mikaelarguedas** [comment]
> But the current patch changes the location in the "catkin" case to be bin rather than lib/class_loader

Yeah as this script has never been released yet that is not a big blocker. I did install it in libexec originally because that's the "ROS way" and I didn't want to pollute the path. As this is a one-time script (only use for migration) I'm going to leave it in libexec and install it there regardless of the build/installation process (and document it's usage).
So I'll just revert the last commit to end up with:
- library and executable from previous release will still be installed at the same place as before
- the newly added migration script will be installed in libexec and will have to be invoked via rosrun or with a full path to the executable

Thanks @dirk-thomas and @tfoote for the online and IRL feedback
Sorry @dbcesar for hijacking your PR :confused:

**Comment by dbcesar** [comment]
@mikaelarguedas not a problem at all

**Comment by mikaelarguedas** [comment]
OK squashed my commits together and kept the original one. CI is happy, merging..
thanks @dbcesar for the fix!

**Pull request merged**
