### PR TITLE
Update ROS 1 package maintainers.

### PR DESCRIPTION
**Pull request by hidmic**
Precisely what the title says, for `ros1` support.

### CODE REVIEW

**Review by nuclearsandwich — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
There is a `noetic-devel` branch as well but it isn't the default and it has not been used for a release to the best of my memory.

Edit: actually it has https://github.com/ros/class_loader/tree/noetic-devel, 0.5.0

**Comment by hidmic** [comment]
@nuclearsandwich just re-targeted this PR against ` noetic-devel`. Should we make it the default? WDYT @mjcarroll ?

**Comment by nuclearsandwich** [comment]
>  Should we make it the default?

Probably. It was only time and attention deficit after an oversight that kept me from doing so.

**Comment by mjcarroll** [comment]
>  Should we make it the default? WDYT @mjcarroll ?

Agree, we should make it default.

**Review by mjcarroll — APPROVED** [review]

**Pull request merged**
