### PR TITLE
fixed usage of deprecated console bridge functions

### PR DESCRIPTION
**Pull request by jmachowinski**

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@jmachowinski we'll reconsider this change once there are changes significant enough to justify branching kinetic (and newer) out of master

**Comment by jpetereit** [comment]
Please do reconsider accepting this PR since the use of the deprecated macros causes lots and lots of warnings when using clang (see #49).

**Comment by mikaelarguedas** [comment]
@jpetereit As mentionned in https://github.com/ros/class_loader/pull/37#issuecomment-276808799 this PR cannot be merged as is, These new macros have been introduced in console_bridge v0.3.0 and ubuntu was shipping 0.2.5 until xenial. So we have 2  possible solutions:
- Modify this PR / open another PR that checks the version of console_bridge and defines the macros according to the version
- wait until there are features that require maintaining two versions of the code and integrate these changes on the branch targeting kinetic and later (note that I don't consider fixing warnings generated by flags and compilers not officially targetted to be "feature" but "nice to have bugfix" that in my opinion doesn't justify maintaining 2 versions of the code)

**Comment by jpetereit** [comment]
@mikaelarguedas I can see your point. What about introducing something like

```cpp
#ifndef CONSOLE_BRIDGE_logInform
#  define CONSOLE_BRIDGE_logInform logInform
#endif
```

just after the console_bridge includes and then just using `CONSOLE_BRIDGE_logInform` in the respective places? Then it would be as easy as removing the ifdefs if you shoud want to switch to the nondeprecated names in the future.

**Comment by jmachowinski** [comment]
Uhm, what is the ros policy on API beakage ? I mean Xenial has been out for more than one year now,
why do you still need to be compatible to console_bridge 2.5 ? Other packages already moved forward.

**Comment by mikaelarguedas** [comment]
@jmachowinski this branch is used for all ROS distributions (including indigo that targets trusty so uses 2.5) So making the change without staying compatible with 2.5 will break the indigo builds

----
> @mikaelarguedas I can see your point. What about introducing something like
```
> #ifndef CONSOLE_BRIDGE_logInform
#  define CONSOLE_BRIDGE_logInform logInform
#endif
```
> just after the console_bridge includes and then just using CONSOLE_BRIDGE_logInform in the respective places? Then it would be as easy as removing the ifdefs if you shoud want to switch to the nondeprecated names in the future.

@jpetereit this looks sensible to me. Once a PR sublmitted with these changes I'll give it a try on all targeted platforms to make sure we didn't break along the way

**Comment by mikaelarguedas** [comment]
@jmachowinski @jpetereit Please see follow-up PR #52 implementing @jpetereit suggestion.

**Comment by jmachowinski** [comment]
closing this in favor for #52

**Pull request closed without merging**
