### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by mgrrx**
generated using 2to3

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
It doesn't appear that this change remains compatible with Python2. Since that's the case it likely cannot target `melodic-devel`.

**Comment by mgrrx** [comment]
the changes are compatible with python 2.

**Comment by dirk-thomas** [comment]
> the changes are compatible with python 2.

I would second that after reading the diff. :+1:

**Comment by nuclearsandwich** [comment]
Thanks for the input. I hadn't had a chance to try it locally but made assumptions based on the removal of future imports.

**Comment by nuclearsandwich** [comment]
Thanks for contributing!

**Pull request merged**
