### PR TITLE
Poco detection is too confident when seeing /usr/include/Foundation

### PR DESCRIPTION
**Pull request by v4hn**
That folder is also provided by gnustep-base. Ubuntu encapsulates the gnustep
headers in a GNUstep folder, however the project itself installs to
/usr/include/Foundation and other linux distributions(Archlinux, Gentoo,
Lunar-Linux, ...) respect this.

### CODE REVIEW

**Comment by tfoote** [comment]
+1

**Comment by dirk-thomas** [comment]
Relying on a arbitrary file like AbstractCache.h looks a bit weird. Couldn't we either just check for existence of the folder `${Poco_INCLUDE_DIR}/Foundation/include/Poco` or even better check the existence of the specific file we actually include `${Poco_INCLUDE_DIR}/Foundation/include/Poco/SharedLibrary.h`?

**Comment by v4hn** [comment]
Relying on the existence of the base folder is even more weird in my opinion.

I just used the same criterion as used above in line 103 in both files.
If you want to check for a different file(SharedLibrary.h is fine as well)
you should change these lines as well.

I'll change the pull request accordingly...

**Comment by dirk-thomas** [comment]
+1

**Pull request merged**
