### PR TITLE
Remove travis.

### PR DESCRIPTION
**Pull request by clalancette**
Travis no longer supports open-source, and we have test coverage
via the ROS buildfarm anyway.  Just remove it here.

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

### CODE REVIEW

**Review by hidmic — APPROVED** [review]
Thanks Chris! I wonder if we should do the same about `appveyor`.

**Comment by clalancette** [comment]
> Thanks Chris! I wonder if we should do the same about `appveyor`.

Yeah, I was thinking about it, but ultimately decided to do it separately.  The main reason is that `appveyor` does give us some coverage that the buildfarm does not, i.e. Windows testing.  So I was thinking that we should actually fix it rather than remove it.

**Review by nuclearsandwich — APPROVED** [review]
:+1: for removing Travis and Appveyor. They've already been removed from the ROS 1 branches and I think there was even an attempt to remove them in ROS 2 that got accidentally unwound when resolving a merge.

**Comment by clalancette** [comment]
I'm not going to run additional CI here since this isn't a code change.  Thanks for the reviews!

**Pull request merged**
