### PR TITLE
Fix include order for cpplint

### PR DESCRIPTION
**Pull request by jacobperron**
Relates to https://github.com/ament/ament_lint/pull/324

### CODE REVIEW

**Comment by jacobperron** [comment]
The appveyor job has been failing since August 2020 (https://github.com/ros/class_loader/issues/164). Perhaps we should just remove it considering we have Windows coverage via ci.ros2.org?

**Review by gbiggs — APPROVED** [review]
LGTM

**Comment by gbiggs** [comment]
CI:

- Linux [Build Status](https://ci.ros2.org/job/ci_linux/15930/)
- Linux (aarch64) [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/10605/)
- Windows [Build Status](https://ci.ros2.org/job/ci_windows/16254/)

**Comment by gbiggs** [comment]
What is the Appveyor job supposed to do?

**Comment by jacobperron** [comment]
> What is the Appveyor job supposed to do?

Test the package on Windows, I suppose. It was added in 2015 (https://github.com/ros/class_loader/pull/28); though  it doesn't predate ci.ros2.org, so maybe it was supposed to provide additional test coverage. @wjwwood I know it's ancient history, but do you know the origin story?

**Comment by wjwwood** [comment]
Not sure, but it may have been just covering class_loader itself before we were running ci.ros2.org on everything.

**Pull request merged**
